version: "3"

vars:
  BINARY_NAME: sesh
  TARGET_DIR: target
  RELEASE_DIR: "{{.TARGET_DIR}}/release"
  DEBUG_DIR: "{{.TARGET_DIR}}/debug"
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  BUILD_DATE:
    sh: date -u '+%Y-%m-%d_%H:%M:%S'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  build:
    desc: Build the binary in release mode
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
    generates:
      - "{{.RELEASE_DIR}}/{{.BINARY_NAME}}"
    cmds:
      - cargo build --release

  build:debug:
    desc: Build the binary in debug mode
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
      - "Cargo.lock"
    generates:
      - "{{.DEBUG_DIR}}/{{.BINARY_NAME}}"
    cmds:
      - cargo build

  install:
    desc: Install the binary to $CARGO_HOME/bin or ~/.cargo/bin
    deps: [build]
    cmds:
      - cargo install --path .

  run:
    desc: "Run the application (usage: task run -- [args])"
    cmds:
      - cargo run -- {{.CLI_ARGS}}

  dev:
    desc: Run in development mode (rebuild on changes)
    cmds:
      - cargo watch -x run

  test:
    desc: Run tests
    cmds:
      - cargo test --verbose

  test:coverage:
    desc: Run tests and generate coverage report
    cmds:
      - cargo tarpaulin --out Html --output-dir coverage
      - echo "Coverage report generated at coverage/index.html"

  test:short:
    desc: Run tests without output capture
    cmds:
      - cargo test -- --nocapture

  bench:
    desc: Run benchmarks
    cmds:
      - cargo bench

  fmt:
    desc: Format code
    cmds:
      - cargo fmt

  fmt:check:
    desc: Check if code is formatted
    cmds:
      - cargo fmt -- --check

  clippy:
    desc: Run clippy linter
    cmds:
      - cargo clippy -- -D warnings

  check:
    desc: Run all checks (fmt, clippy, test)
    cmds:
      - task: fmt:check
      - task: clippy
      - task: test

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean
      - rm -rf coverage/

  clean:all:
    desc: Clean all generated files including dependencies
    cmds:
      - task: clean
      - rm -rf ~/.cargo/registry/cache/
      - rm -rf ~/.cargo/git/db/

  deps:
    desc: Update dependencies
    cmds:
      - cargo update

  deps:check:
    desc: Check for outdated dependencies
    cmds:
      - cargo outdated

  doc:
    desc: Build documentation
    cmds:
      - cargo doc --no-deps

  doc:open:
    desc: Build and open documentation in browser
    cmds:
      - cargo doc --no-deps --open

  help:
    desc: Show help for the built binary
    deps: [build]
    cmds:
      - "{{.RELEASE_DIR}}/{{.BINARY_NAME}} --help"

  release:
    desc: "Create a new release (usage: task release -- --type [patch|minor|major])"
    cmds:
      - ./scripts/release.sh {{.CLI_ARGS}}

  release:patch:
    desc: Create a new patch release (e.g., 0.1.6 -> 0.1.7)
    cmds:
      - ./scripts/release.sh --type patch

  release:minor:
    desc: Create a new minor release (e.g., 0.1.6 -> 0.2.0)
    cmds:
      - ./scripts/release.sh --type minor

  release:major:
    desc: Create a new major release (e.g., 0.1.6 -> 1.0.0)
    cmds:
      - ./scripts/release.sh --type major
