version: "3"

vars:
  BINARY_NAME: sesh
  DIST_DIR: dist
  MAIN_PACKAGE: .
  GO_FILES:
    sh: find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./.direnv/*"
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  BUILD_DATE:
    sh: date -u '+%Y-%m-%d_%H:%M:%S'
  BUILT_BY:
    sh: whoami

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  build:
    desc: Build the binary
    sources:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    generates:
      - "{{.DIST_DIR}}/{{.BINARY_NAME}}"
    cmds:
      - mkdir -p {{.DIST_DIR}}
      - >
        go build
        -ldflags "
        -X github.com/benoctopus/sesh/cmd.version={{.VERSION}}
        -X github.com/benoctopus/sesh/cmd.commit={{.COMMIT}}
        -X github.com/benoctopus/sesh/cmd.buildDate={{.BUILD_DATE}}
        -X github.com/benoctopus/sesh/cmd.builtBy={{.BUILT_BY}}
        "
        -o {{.DIST_DIR}}/{{.BINARY_NAME}}
        {{.MAIN_PACKAGE}}

  build:debug:
    desc: Build the binary with debug symbols
    cmds:
      - mkdir -p {{.DIST_DIR}}
      - >
        go build
        -gcflags="all=-N -l"
        -ldflags "
        -X github.com/benoctopus/sesh/cmd.version={{.VERSION}}
        -X github.com/benoctopus/sesh/cmd.commit={{.COMMIT}}
        -X github.com/benoctopus/sesh/cmd.buildDate={{.BUILD_DATE}}
        -X github.com/benoctopus/sesh/cmd.builtBy={{.BUILT_BY}}
        "
        -o {{.DIST_DIR}}/{{.BINARY_NAME}}
        {{.MAIN_PACKAGE}}

  install:
    desc: Install the binary to $GOPATH/bin
    deps: [build]
    cmds:
      - go install {{.MAIN_PACKAGE}}

  run:
    desc: "Run the application (usage: task run -- [args])"
    cmds:
      - go run {{.MAIN_PACKAGE}} {{.CLI_ARGS}}

  dev:
    desc: Run in development mode (rebuild on changes)
    cmds:
      - |
        while true; do
          task build
          echo "Watching for changes... (Ctrl+C to stop)"
          inotifywait -qre close_write . --include '\.go$' || fswatch -1 -r --include='\.go$' . || sleep 2
        done

  test:
    desc: Run tests
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...

  test:coverage:
    desc: Run tests and show coverage
    cmds:
      - task: test
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  test:short:
    desc: Run tests (short mode)
    cmds:
      - go test -short ./...

  bench:
    desc: Run benchmarks
    cmds:
      - go test -bench=. -benchmem ./...

  fmt:
    desc: Format code
    cmds:
      - go tool gofumpt -l -w .
      - go tool golines -w --max-len=120 --base-formatter=gofumpt .

  fmt:check:
    desc: Check if code is formatted
    cmds:
      - gofumpt -l .
      - test -z "$(gofumpt -l .)"

  tidy:
    desc: Tidy go.mod
    cmds:
      - go mod tidy

  verify:
    desc: Verify dependencies
    cmds:
      - go mod verify

  check:
    desc: Run all checks (fmt, lint, test)
    cmds:
      - task: fmt:check
      - task: test

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.DIST_DIR}}
      - rm -f coverage.out coverage.html
      - go clean -cache -testcache

  clean:all:
    desc: Clean all generated files including dependencies
    cmds:
      - task: clean
      - rm -rf vendor/
      - go clean -modcache

  deps:
    desc: Download dependencies
    cmds:
      - go mod download

  cobra:add:
    desc: "Add a new cobra command (usage: task cobra:add -- commandName)"
    cmds:
      - cobra-cli add {{.CLI_ARGS}}

  init:db:
    desc: Initialize the database (placeholder for future implementation)
    cmds:
      - echo "Database initialization not yet implemented"

  help:
    desc: Show help for the built binary
    deps: [build]
    cmds:
      - "{{.DIST_DIR}}/{{.BINARY_NAME}} --help"

  release:
    desc: "Create a new release (usage: task release -- --type [patch|minor|major])"
    cmds:
      - ./scripts/release.sh {{.CLI_ARGS}}

  release:patch:
    desc: Create a new patch release (e.g., 0.1.6 -> 0.1.7)
    cmds:
      - ./scripts/release.sh --type patch

  release:minor:
    desc: Create a new minor release (e.g., 0.1.6 -> 0.2.0)
    cmds:
      - ./scripts/release.sh --type minor

  release:major:
    desc: Create a new major release (e.g., 0.1.6 -> 1.0.0)
    cmds:
      - ./scripts/release.sh --type major
